insert into T_TR_SWITCH(TRIGGER_NAME,SWITCH_FOR,STATUS) VALUES(
     'TRI_BD_T_SWITCH_CONTROL',
     'T_SWITCH_CONTROL',
     '1'
);
insert into T_TR_SWITCH(TRIGGER_NAME,SWITCH_FOR,STATUS) VALUES(
     'TRI_BI_T_SWITCH_CONTROL',
     'T_SWITCH_CONTROL',
     '1'
);
insert into T_TR_SWITCH(TRIGGER_NAME,SWITCH_FOR,STATUS) VALUES(
     'TRI_BU_T_SWITCH_CONTROL',
     'T_SWITCH_CONTROL',
     '1'
);
