CREATE TABLE T_TR_SWITCH(
    TRIGGER_NAME VARCHAR2(100),
    SWITCH_FOR   VARCHAR2(100),
    STATUS       VARCHAR2(1)
);

COMMENT ON TABLE T_TR_SWITCH IS '触发器开关表';
COMMENT ON COLUMN T_TR_SWITCH.TRIGGER_NAME IS '触发器名称';
COMMENT ON COLUMN T_TR_SWITCH.SWITCH_FOR IS '表名称';
COMMENT ON COLUMN T_TR_SWITCH.STATUS IS '触发器状态(1: 有效，0: 无效)';

CREATE INDEX IDX_T_TR_SWITCH_FOR ON T_TR_SWITCH(SWITCH_FOR) storage (initial 64k next 64k);